name: CI

on: [push, pull_request]

jobs:
  build:
    name: JDK ${{ matrix.java_version }}
    runs-on: macOS-latest
    strategy:
      matrix:
        java_version: [1.8]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java_version }}
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.0.5
      - name: Configure Gradle
        # Initial gradle configuration, install dependencies, etc
        run: ./gradlew help
        working-directory: ./android
      - name: Build project
        run: ./gradlew assemble --stacktrace
        working-directory: ./android
      # - name: Run tests
      #   run: ./gradlew test --stacktrace
      - name: Run instrumentation tests
        uses: malinskiy/action-android/emulator-run-cmd@release/0.0.5
        with:
          cmd: ./gradlew connectedCheck --stacktrace
          api: 18
          tag: default
          abi: x86
        working-directory: ./android
